services:
  vault-unseal:
    image: hashicorp/vault:latest
    cap_add:
      - IPC_LOCK
    user: "root"
    volumes:
      - ./vault/config:/vault/config
      - vault-unseal-data:/vault/data/unseal-data
      - ./start.sh:/start.sh
      - ./setup.sh:/setup.sh
      - ./policy.hcl:/policy.hcl
    entrypoint: ["/start.sh"]
    networks:
      - vault-internal

volumes:
  vault-unseal-data:
    driver: "local"
    name: "${VAULT_UNSEAL_VOLUME_DATA_NAME:-vault_unseal_data}"
