services:
  vault-slave2:
    image: hashicorp/vault:latest
    cap_add:
      - IPC_LOCK
    user: "root"
    volumes:
      - ./vault/config:/vault/config
      - vault-slave2-data:/vault/data/slave2-data
      - ./start.sh:/start.sh
    environment:
      VAULT_TOKEN: "${VAULT_TRANSIT_TOKEN}"
    entrypoint: ["/start.sh"]
    networks:
      - vault-internal
    depends_on:
      - vault-unseal

volumes:
  vault-slave2-data:
    driver: "local"
    name: "${VAULT_LEADER_VOLUME_DATA_NAME:-vault_slave2_data}"
