services:
  vault-leader:
    image: hashicorp/vault:latest
    cap_add:
      - IPC_LOCK
    user: "root"
    volumes:
      - ./vault/config:/vault/config
      - vault-data:/vault/data/leader-data
      - ./start.sh:/start.sh
    environment:
      VAULT_TOKEN: "${VAULT_TRANSIT_TOKEN}"
    entrypoint: ["/start.sh"]
    networks:
      - vault-internal
    depends_on:
      - vault-unseal

volumes:
  vault-data:
    driver: "local"
    name: "${VAULT_LEADER_VOLUME_DATA_NAME:-vault_leader_data}"
