"""Device sessions table added

Revision ID: 2d7fb677f5a9
Revises: e36edbad9d63
Create Date: 2026-08-05 13:13:44.709739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d7fb677f5a9'
down_revision: Union[str, Sequence[str], None] = 'e36edbad9d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('client_device_id', sa.UUID(), nullable=False),
    sa.Column('device_name', sa.String(length=256), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_seen_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('idle_expires_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("NOW() + INTERVAL '180 days'"), nullable=False),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('fk_device_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_sessions')),
    schema='auth'
    )
    op.create_index('ix_device_sessions_idle_expires_at', 'device_sessions', ['idle_expires_at'], unique=False, schema='auth')
    op.create_index('ix_device_sessions_user_id', 'device_sessions', ['user_id'], unique=False, schema='auth')
    op.create_index('ix_device_sessions_user_id_client_device_id', 'device_sessions', ['user_id', 'client_device_id'], unique=False, schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_device_sessions_user_id_client_device_id', table_name='device_sessions', schema='auth')
    op.drop_index('ix_device_sessions_user_id', table_name='device_sessions', schema='auth')
    op.drop_index('ix_device_sessions_idle_expires_at', table_name='device_sessions', schema='auth')
    op.drop_table('device_sessions', schema='auth')
    # ### end Alembic commands ###
