"""Overall table corrections(device sessions and users

Revision ID: 43e64ae94cbe
Revises: 93e074d9391b
Create Date: 2026-07-31 11:44:22.852405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43e64ae94cbe'
down_revision: Union[str, Sequence[str], None] = '93e074d9391b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device_sessions', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.UUID(),
               existing_nullable=False,
               schema='auth')
    op.alter_column('device_sessions', 'ip_address',
               existing_type=postgresql.INET(),
               nullable=True,
               schema='auth')
    op.alter_column('device_sessions', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='auth')
    op.create_index('ix_device_sessions_idle_expires_at', 'device_sessions', ['idle_expires_at'], unique=False, schema='auth')
    op.create_index('ix_device_sessions_user_id', 'device_sessions', ['user_id'], unique=False, schema='auth')
    op.create_index('ix_device_sessions_user_id_client_device_id', 'device_sessions', ['user_id', 'client_device_id'], unique=False, schema='auth')
    op.drop_column('device_sessions', 'revokation_reason', schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_sessions', sa.Column('revokation_reason', sa.VARCHAR(), autoincrement=False, nullable=False), schema='auth')
    op.drop_index('ix_device_sessions_user_id_client_device_id', table_name='device_sessions', schema='auth')
    op.drop_index('ix_device_sessions_user_id', table_name='device_sessions', schema='auth')
    op.drop_index('ix_device_sessions_idle_expires_at', table_name='device_sessions', schema='auth')
    op.alter_column('device_sessions', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='auth')
    op.alter_column('device_sessions', 'ip_address',
               existing_type=postgresql.INET(),
               nullable=False,
               schema='auth')
    op.alter_column('device_sessions', 'id',
               existing_type=sa.UUID(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               schema='auth')
    # ### end Alembic commands ###
