"""Refresh token

Revision ID: 823a5a09fe16
Revises: 2d7fb677f5a9
Create Date: 2026-08-17 21:45:47.159704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '823a5a09fe16'
down_revision: Union[str, Sequence[str], None] = '2d7fb677f5a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_session_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('issued_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('replaced_by_id', sa.UUID(), nullable=True),
    sa.Column('consumed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_session_id'], ['auth.device_sessions.id'], name=op.f('fk_refresh_tokens_device_session_id_device_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['auth.refresh_tokens.id'], name=op.f('fk_refresh_tokens_replaced_by_id_refresh_tokens'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('replaced_by_id', name=op.f('uq_refresh_tokens_replaced_by_id')),
    schema='auth'
    )
    op.create_index(op.f('ix_refresh_tokens_device_session_id'), 'refresh_tokens', ['device_session_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False, schema='auth')
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True, schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens', schema='auth')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens', schema='auth')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens', schema='auth')
    op.drop_index(op.f('ix_refresh_tokens_device_session_id'), table_name='refresh_tokens', schema='auth')
    op.drop_table('refresh_tokens', schema='auth')
    # ### end Alembic commands ###
