"""Device sessions table added

Revision ID: 93e074d9391b
Revises: e36edbad9d63
Create Date: 2026-07-31 11:28:40.410247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93e074d9391b'
down_revision: Union[str, Sequence[str], None] = 'e36edbad9d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_sessions',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('client_device_id', sa.UUID(), nullable=False),
    sa.Column('device_name', sa.String(length=256), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_seen_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('idle_expires_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("NOW() + INTERVAL '180 days'"), nullable=False),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revokation_reason', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('fk_device_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_sessions')),
    schema='auth'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_sessions', schema='auth')
    # ### end Alembic commands ###
