"""family_id no longer exists

Revision ID: b1530c80c950
Revises: 823a5a09fe16
Create Date: 2026-09-03 13:58:00.373639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1530c80c950'
down_revision: Union[str, Sequence[str], None] = '823a5a09fe16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens', schema='auth')
    op.drop_column('refresh_tokens', 'family_id', schema='auth')
    op.drop_constraint(op.f('ck_users_user_role'), 'users', schema='auth', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('ck_users_user_role'), 'users', "role::text = ANY (ARRAY['user'::character varying, 'moderator'::character varying, 'admin'::character varying]::text[])", schema='auth')
    op.add_column('refresh_tokens', sa.Column('family_id', sa.UUID(), autoincrement=False, nullable=False), schema='auth')
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False, schema='auth')
    # ### end Alembic commands ###
